apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
data:
  config.yaml: |
    server:
      port: 5000
    database:
      host: db.internal.com
      port: 5555
      user: user
      password: password